classDiagram
    class automobile {
        -targa: string
        -modello: string
        -categoria: string
        -disponibilita: string
        +automobile(targa: string, modello: string, categoria: string, disponibilita: string)
        +getTarga(): string
        +getModello(): string
        +getCategoria(): string
        +getDisponibilita(): string
        +setDisponibilita(disponibilita: string): void
    }

    class AgenziaNoleggio {
        -automobili: automobile[]
        -noleggi: automobile[]
        +agenziaNoleggio()
        +aggiungiAutomobile(targa: string, modello: string, categoria: string): void
        +noleggiaAutomobile(targa: string): void
        +visualizzaAutomobiliDisponibili(): void
        +visualizzaNoleggi(): void
    }   

    


    automobile "1" --> "*" AgenziaNoleggio: automobili






